# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go Build

on:
  workflow_dispatch:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]
  release:
    types: [ published ]


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.5'

    - name: Build
      env:
        GOOS: linux
        GOARCH: amd64
        CGO_ENABLED: 0
      run: go build -o password-api

    - name: Test
      run: go test -v ./...

    - name: Go Security Test
      run: |
        go install github.com/securego/gosec/v2/cmd/gosec@latest
        gosec .

    - name: Docker Build
      run: docker build . --file Dockerfile --tag password-generator-api:${GITHUB_REF##*/}